### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bazilinskyy** [bazilinskyy/coupled-sim#15]
Finalise documentation as `README.md`. Possibly move to https://github.com/bazilinskyy/coupled-sim/wiki later.

**Comment by bazilinskyy** [comment]
@Lynx32, I am missing:
- [x] How to edit/change buttons on the UI of host/client.
- [x] Workflow of clicking around those buttons to configure host/client. It is started at https://github.com/bazilinskyy/coupled-sim#running-the-project

**Comment by Lynx32** [comment]
I have updated readme with a section about running experiments.
I am not sure what you mean in the first request.

**Comment by bazilinskyy** [comment]
How to edit/add these buttons. 
![image](https://user-images.githubusercontent.com/274115/66569697-c5df7300-eb74-11e9-98b4-15f02b15a1a3.png)
