### ISSUE TITLE
Update rate of speedometer

### ISSUE THREAD

**Issue by bazilinskyy** [bazilinskyy/coupled-sim#20]
We fixed the jumps in value of speed on the speedometer by reducing the update rate. Now, the speed changes with big jumps. We should make it more smooth.

**Comment by Lynx32** [comment]
There is a speedometer "clock" now. Does it resolve the issue?

**Comment by bazilinskyy** [comment]
Which branch? Or could you send an image here? I think the digital speedometer may be better, as it is easier to monitor the speed, in case we need to give strict limits on the speed to the participant. Perhaps it is possible, to add a flag to the cars to switch between two? In this case, the digital speedometer would still need to be made 'smooth'.

**Comment by Lynx32** [comment]
![image](https://user-images.githubusercontent.com/10687687/66482634-ad535800-eaa3-11e9-8a18-b08899cce230.png)

**Comment by bazilinskyy** [comment]
Nice. I guess turn indicators will be here as well? And could you make a flag to choose which speedometer to use?

**Comment by Lynx32** [comment]
Turn indicators are there as well. Logic is prepared to handle both digital as previously was and analog. If both are configured in prefab, it is just a matter of disabling/enabling game objects. If you really think flag to control it is needed it can be added, but imo it would be better to leave it as a car prefab definition step.

**Comment by bazilinskyy** [comment]
Sure, as a prefab is also good. Please also update in the readme. Thank you!
